### ISSUE TITLE
Document usage of pg_hint_plan

### ISSUE THREAD

**Issue by staticlibs** [wiltondb/wiltondb#1]
WiltonDB includes [pg_hint_plan](https://github.com/ossc-db/pg_hint_plan) extension that allows to use hints in T-SQL queries over TDS connection. There are a few [examples of its usage in tests](https://github.com/babelfish-for-postgresql/babelfish_extensions/tree/952244f7801f87311eece24b057e5dc33ae25a8b/test/JDBC/input/pg_hint_plan), but no documentation so far. It makes sense to document its intended usage in wiki with simple hint examples.

**Comment by suprio-amzn** [comment]
The documentation for usage of T-SQL hints in Babelfish is at https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Using-T%E2%80%90SQL-query-hints-to-improve-Babelfish-query-performance.

**Comment by staticlibs** [comment]
Thanks for the link! Can confirm that is works on Windows the same way, closing this issue.
