### ISSUE TITLE
What is the version of WiltonDB?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#22]
What is the version of WiltonDB? Post installation, I could see WiltonDB title as 3.3, but version as 8.13.1.0. Please find below attached screenshot

![image](https://github.com/wiltondb/wiltondb/assets/89133439/39d60cce-2d38-4262-90a1-0876cc0c2e6d)

**Comment by staticlibs** [comment]
`3.3` is a version of Babelfish that WiltonDB is originally based on. It defines the system catalogs structure, that can be changed in minor Babelfish updates, but is kept the same in WiltonDB 3.3. It is treated as part of a package name (also included in Windows Service name), to be able to distinguish it from possible future major WiltonDB versions.

`8.13.1.0` is an MSI package version:

 - `8` - refers to the [engine](https://github.com/wiltondb/postgresql_modified_for_babelfish) version, corresponds to `WILTON_3_3-8` tag
 -  `13`- refers to the [extensions](https://github.com/wiltondb/babelfish_extensions) version, corresponds to `WILTON_3_3-13` tag
 - `1` - refers to [MSI packaging scripts](https://github.com/wiltondb/wdb_windows_msi), can be incremented if MSI needs to be rebuilt for the same engine+extensions tag
 - `0` - 4th part of MSI version is ignored by Windows Installer subsystem for update version comparison, it is always kept as 0.

**Comment by psrinivasa2** [comment]
thanks @staticlibs
