### ISSUE TITLE
Unmapped error found. Code: 2600, Message: cache lookup failed for function 0, Affected entities: Employee table

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#24]
Hi @staticlibs, Morning :-)

Any idea on below error which I get while connecting from application and update entry of table

Unmapped error found. Code: 2600, Message: cache lookup failed for function 0

**Comment by staticlibs** [comment]
Hi @psrinivasa2 , this is Postgres internal error, it may indicate data inconsistency or data corruption. The same intermittent error [was reported](https://www.postgresql.org/message-id/flat/20230929163739.3bea46e5.pfortin%40pfortin.com) on vanilla Postgres version 15.4 (the same version WiltonDB is based on).

Can you please do the following to narrow this down:

1. export the problematic T-SQL DB with [wdb_backup](https://github.com/wiltondb/wiltondb/wiki/WiltonDB-Backup-GUI-tool)
2. initialize new DB cluster from scratch (for example: stop windows service, rename data dir, rerun the installer)
3. restore problematic DB dump into clean DB cluster
4. run the workload that uncovers this issue

Assuming this is reproducible (this also applies to problems in #23), would it be possible for you to do one of the following options:

1. anonymize confidential data in this T-SQL DB and share the dump with me privately (like GDrive link to email)
2. set up a secure remote workplace (RDP etc) in your environment, where I can connect, set up dev environment and debug Postgres/Babelfish internals on your data with this data never leaving your premises

For such intermittent/hard to reproduce problems, I really would like to get to the bottom. Just only the error message itself is not enough to investigate this. If options above are not possible, then you need to get some engineer on your side to enable Postgres and Babelfish verbose logging (what exactly to enable depends on a problem - can elaborate), reproduce the problem, and then anonymize and share verbose logs.

**Comment by psrinivasa2** [comment]
thanks for the details @staticlibs  I will check on it

**Comment by psrinivasa2** [comment]
Hi @staticlibs, Good Morning :-) 
Please find the attached log file, this does not have any confidential data, hence sharing it here.

[postgresql-Fri.log](https://github.com/user-attachments/files/16189702/postgresql-Fri.log)

**Comment by psrinivasa2** [comment]
log_statement = 'all'
the above statement already been there in postgresql.conf. where should I mention babelfishpg_tds.tds_debug_log_level = 2, which config file?
![image](https://github.com/user-attachments/assets/b76e8240-ae8b-411f-a9b9-a712254cfdb7)

**Comment by psrinivasa2** [comment]
one more thing to convey if it get clash, I have already enabled select * from pg_stat_statements feature

**Comment by staticlibs** [comment]
I suggest to set these options with `wdb_config` (it is included with installer in `bin` dir) - it will reload the server settings automatically:

![cache_01](https://github.com/user-attachments/assets/70effbe8-e5e0-4768-b0c2-2735893221cf)

On your screenshot `log_statement` is commented out with `#`, when set with `wdb_config` it will be written to `postgresql.auto.conf`.

**Comment by psrinivasa2** [comment]
Apologies, Now updated the setting and restarted WiltonDB, Alex @staticlibs, I have emailed you the log file details, please check


![image](https://github.com/user-attachments/assets/e66fe237-d7e0-40e4-95d7-63f422da91e1)
![image](https://github.com/user-attachments/assets/5d5b5d27-3a9e-424f-8355-4960dbf1fb5e)

**Comment by staticlibs** [comment]
@psrinivasa2 , confirming that I've received the log. Will analyze it and report back.

**Comment by psrinivasa2** [comment]
@staticlibs  where are we on releasing the detail log installer to troubleshoot this issue?

**Comment by staticlibs** [comment]
@psrinivasa2 , installer with support for printing backtraces for all reported errors should be ready either later today or tomorrow. It should allow to track the problem to the exact place (hopefully - exact T-SQL function) where it happens.

**Comment by staticlibs** [comment]
@psrinivasa2 , published debug installer [release page](https://github.com/wiltondb/wiltondb/releases/tag/3.3-10-15-0-rc2), `wiltondb3.3_debug_10.15.0.msi ` download there. If possible, please run the problematic workload on this version, it should include detailed backtraces for all error messages. This version may be up to 1.5 times slower than the normal one.

Additionally it would be better to set:

```
babelfishpg_tds.tds_debug_log_level = 3
```

This TDS setting is unrelated to backtraces, it will log all networking packets. It makes log even more verbose, but problematic SQL was not logged for some reason when it is set to `2`.

**Comment by psrinivasa2** [comment]
Thanks much Alex @staticlibs

**Comment by staticlibs** [comment]
@psrinivasa2 , with the help of your detailed logs I've reproduced the problem and found the root cause. The problematic query uses parameter of type `binary(8)`. Babelfish confuses this parameter type with [rowversion](https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver16) one (that itself is defined as binary of size 8), so it is unable to find type conversion function for it and fails with error about "function 0" (where 0 is `InvalidOid`). I have a fix and will create updated MSI over the weekend.

As a workaround in client app, the problem should not happen if you change `binary` to `varbinary` for that query or change the length from `8` to some other value.

**Comment by psrinivasa2** [comment]
thanks @staticlibs

**Comment by staticlibs** [comment]
For the record, link to the upstream Babelfish issue I've opened for this problem - [#2762](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2762).

**Comment by psrinivasa2** [comment]
Hi Alex,
Getting similar issue in other scenario with below error message

Code: 1088, Message: Cannot insert an explicit value into a timestamp column.

I have mailed you the table structure and log file details

**Comment by staticlibs** [comment]
@psrinivasa2 

This problem is unrelated to `binary(8)`, I've created a separate issue for it - #64.
