### ISSUE TITLE
Question: Do we have any automatic mechanism to clear the older log files or this needs to be handled manually from customer end?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#25]
Question: Do we have any automatic mechanism to clear out the older log files or this needs to be handled manually from customer end?

C:\Program Files\WiltonDB Software\wiltondb3.3\data\log

**Comment by staticlibs** [comment]
This should work by default, default installation only keeps logs for the last week. `log_filename` option is set to `postgresql-%a.log` without including timestamp into the file name and `log_truncate_on_rotation` is `on`, so the file should be overwritten after a week ([other logging options](https://www.postgresql.org/docs/15/runtime-config-logging.html)).

**Comment by psrinivasa2** [comment]
thanks alex
