### ISSUE TITLE
Question: How about babckup and restore mechanism in wiltonDB and also If I uninstall my wiltonDB without taking backup how the behavior will be? ?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#27]
Question: How about babckup and restore mechanism in wiltonDB and also If I uninstall my wiltonDB without taking backup how the behavior will be? ?

**Comment by staticlibs** [comment]
About backup/restore in general: please see [Backup and restore overview in Babelfish](https://github.com/wiltondb/wiltondb/wiki/Backup-and-restore-overview-in-Babelfish) and other pages linked there. There are pending fixes to `wdb_backup` - tracked in #16.

About installer: when installation is done and `<install_dir>/data` dir is empty - installer will [initialize DB cluster](https://www.postgresql.org/docs/15/creating-cluster.html) in that directory. If this directory is not empty - initialization is skipped and DB cluster in this dir is used as is.

On uninstall DB cluster files are left untouched. On upgrade there is no automatic upgrade of DB cluster and no upgrade-specific  logic overall - basically uninstall and install are performed. If some of Babelfish extensions needs to be upgraded after the installer upgrade - this needs to be done manually, usually running something like following on Postgres port:

```
ALTER EXTENSION "babelfishpg_common" UPDATE TO '3.3.2'
```
