### ISSUE TITLE
Question: How to get transaction log size in postgreSQL

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#32]
Hi Alex @staticlibs,
In SQL, we do have data's and transaction logs which we are taking the size of each database and showing to our support team dashboard on daily job basis

![image](https://github.com/user-attachments/assets/02a0cb26-b86f-417c-8373-087b2ea8cb8f)

In PostgreSQL, for taking the size of database data size, we are using below one,

select (sum(pg_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename)))::int) FROM pg_tables 
WHERE schemaname Like 'employee' || '%';

And we believe WAL files are the equivalent for transaction logs. Any idea on how to get the size of it in query?

![image](https://github.com/user-attachments/assets/3cdebc54-b158-42ef-96be-0ea22f55d8f8)

**Comment by staticlibs** [comment]
The following query can be used to get the size of WAL:

```sql
select sum(size) from pg_ls_waldir()
```

Just I am not sure it will be helpful in this case, because WAL files are not specific to "logical" T-SQL DBs - they correspond to the whole "physical" Postgres DB.

**Comment by psrinivasa2** [comment]
Hi Alex @staticlibs ,
Below query is used to get data size of particular babelfish virtual table, not entire wilton database

select (sum(pg_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename)))::int) FROM pg_tables 
WHERE schemaname Like 'Employee' || '%'; 

Likewise is the any query available to get log size based on babelfish virtual table?

**Comment by staticlibs** [comment]
@psrinivasa2 , I do not think it is possible to get WAL size for a particular Postgres schema (that corresponds to a T-SQL logical DB), at least I don't know how to do it easily.

PS: also, for a table size, it may be better to use [pg_total_relation_size](https://pgpedia.info/p/pg_total_relation_size.html) instead of `pg_relation_size`, as it will include index size.

**Comment by psrinivasa2** [comment]
Thanks for correcting us Alex
