### ISSUE TITLE
Migrating extended properties

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#33]
Hi Alex,
Do you have any idea on migrating extended properties, we are maintaining extended properties for adding descriptions of table, column, etc for giving purpose of table or column,etc. We have around 7500 extended property, when I select SSMS to include extended property column during generate scripts, the SSMS is keep loading and loading, not ends.  Any other smartest way to handle the extended property migration? 

Note we already added the below helper function to handle it for postgreSQL, the problem is exporting from SSMS and some smarter way of generating 7500 lines that can contain below function with necessary inputs of SQL.

-- PROCEDURE: sys.sp_addcomment(text, text, text, text, text, text, text, text)

-- DROP PROCEDURE IF EXISTS sys.sp_addcomment(text, text, text, text, text, text, text, text);

CREATE OR REPLACE PROCEDURE sys.psc_sp_addcomment(
	IN "@name" text,
	IN "@value" text,
	IN "@level0type" text,
	IN "@level0name" text,
	IN "@level1type" text,
	IN "@level1name" text,
	IN "@level2type" text,
	IN "@level2name" text)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	
IF ("@level2type" = 'COLUMN' or "@level2type" = 'CONSTRAINT' or "@level2type" = 'INDEX') THEN
	Execute 'COMMENT ON ' || "@level2type" || ' ' || "@level0name" || '.' || "@level1name" || '.'|| "@level2name" ||' IS ' || chr(39)|| "@value" ||chr(39);
ELSE
	Execute 'COMMENT ON ' || "@level2type" || ' ' || "@level0name" || '.' || "@level1name" ||' IS ' || chr(39)|| "@value" ||chr(39);
END IF;
END;
      
$BODY$;
ALTER PROCEDURE sys.psc_sp_addcomment(text, text, text, text, text, text, text, text)
    OWNER TO wilton;

GRANT EXECUTE ON PROCEDURE sys.psc_sp_addcomment(text, text, text, text, text, text, text, text) TO PUBLIC;

**Comment by staticlibs** [comment]
@psrinivasa2 , I suggest to export extended properties manually in desired format from MSSQL `sys.extended_properties` system view with something like this (including/excluding `sys.columns` as necessary):

```tsql
SELECT  
    O.name AS [Object Name],
    c.name, 
    ep.value AS [Extended property]
FROM 
    sys.columns AS c INNER JOIN 
    sys.all_objects O ON c.object_id = O.object_id LEFT JOIN 
    sys.extended_properties EP ON ep.major_id = c.object_id -- AND ep.minor_id = c.column_id 
WHERE
    O.schema_id = schema_id('schema1')
```
