### ISSUE TITLE
SSMS error with Windows auth: Specified cast is not valid

### ISSUE THREAD

**Issue by staticlibs** [wiltondb/wiltondb#35]
Error message is shown in SSMS during the loading of Object Explorer tree after the successful Windows authentication:

![356225276-b7e05829-64d1-4356-b653-b48786023f8a](https://github.com/user-attachments/assets/6381fc96-f37b-4db3-834e-33471a8fcea3)

Problem only happens with SSMS version 18.x, originally reported [here](https://github.com/wiltondb/wiltondb/issues/18#issuecomment-2275728891).

**Comment by staticlibs** [comment]
The problem happens inside SSMS, there is no DB query error. Also cannot see any real differences between password auth and Windows auth queries from SSMS 18:

 - [out18_pwdauth.log](https://github.com/user-attachments/files/16570758/out18_pwdauth.log)
 - [out18_winauth.log](https://github.com/user-attachments/files/16570759/out18_winauth.log)

Suggested solution is to update to SSMS 19 or 20.

**Comment by psrinivasa2** [comment]
I checked on SSMS 20.2 and no issues there. This ticket can be closed

**Comment by staticlibs** [comment]
Closing the issue.
