### ISSUE TITLE
Question: How about the constraints and index supportability in babelfish?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#39]
Hi @staticlibs ,
How about the constraints and index supportability in babelfish like Forign key, CLUSTERED INDEX, etc

**Comment by staticlibs** [comment]
@psrinivasa2 , constraints, foreign keys and indices are supported in Babelfish. There is no specific handling for clustered indices.

**Comment by psrinivasa2** [comment]
What about primary key? how about the index performance if a column is clustered in SQL and not in babelfish?

**Comment by staticlibs** [comment]
@psrinivasa2 , primary keys are supported. About the performance effect of indices that were created as CLUSTERED in MSSQL - this needs to be looked at on particular data.

**Comment by psrinivasa2** [comment]
how about non clustered index Alex?

**Comment by staticlibs** [comment]
@psrinivasa2 , all indices created in Babelfish can be seen/understood as non-clustered indices in MSSQL.

**Comment by psrinivasa2** [comment]
To understand it clearly, when I execute below statement in babelfish, will it a non-clustered index created for the column?

CREATE TYPE [dbo].[Ids] AS TABLE(
	[Id] [int] NOT NULL,
	PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)

**Comment by staticlibs** [comment]
@psrinivasa2 , in Postgres there is no direct corresponding feature like CLUSTERED index in MSSQL (there is a CLUSTER command, but it is not the same thing). So you can think about all indices created in Babelfish like they are non-clustered ones.
