### ISSUE TITLE
Question: How to run postgreySQL queries via command prompt or powershell something like sqlcmd alternative?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#40]
Hi Alex @staticlibs,
How to run postgreySQL queries via command prompt or powershell something like sqlcmd alternative? I could see a option like psql, but which is not packed with WiltonDB seems

**Comment by staticlibs** [comment]
@psrinivasa2 , yes, "psql.exe" is the main command line tool for Postgres, it is included with WiltonDB distribution.

**Comment by staticlibs** [comment]
@psrinivasa2 , please run "psql.exe" specifying the full path to it in WiltonDB installation dir.

**Comment by psrinivasa2** [comment]
working by navigating to the correct location
