### ISSUE TITLE
wdb_transfer: filter out password in output messages

### ISSUE THREAD

**Issue by staticlibs** [wiltondb/wiltondb#45]
Plain-text DB password can be displayed in error messages, it needs to be filtered out or displayed in masked form.

**Comment by staticlibs** [comment]
![362167870-779aaece-9e45-4572-b8b8-2beaab9dd814](https://github.com/user-attachments/assets/f9e0f10d-5c2c-4e4b-80be-d45716395d22)

**Comment by psrinivasa2** [comment]
Thanks Alex @staticlibs

**Comment by staticlibs** [comment]
Closing as completed.
