### ISSUE TITLE
Command-line interface to wdb_transfer

### ISSUE THREAD

**Issue by staticlibs** [wiltondb/wiltondb#48]
Additional command-line binary `wdb_transfer_cli.exe` needs to be added to Data Transfer tool. It should allow to specify a command - `import` or `export` and a DB connection over TDS. On `export` all tables from the specified DB are exported to a file. On `import` all tables from the specified file are imported to the specified DB (that must contain pre-created empty schema).

**Comment by psrinivasa2** [comment]
Hope you will consider that export operation should return some response on whether it is success or failure, based on which import can be continued.

**Comment by staticlibs** [comment]
@psrinivasa2 

Export and import are being implemented as separate operations. So the tool can be invoked (specifying the DB conn) either for export from this DB or for import to this DB. Zero status code is returned on process success and non-zero on failure.

No plans for a log file in initial version - the same output, that is displayed in GUI, is written to stdout and can be redirected to file by caller as needed.

**Comment by staticlibs** [comment]
Added `wdb_transfer_cli.exe` binary in [wdb_transer-1.4.0](https://github.com/wiltondb/wdb_transfer/releases/tag/1.4.0) update. Also added a few examples to [wiki page](https://github.com/wiltondb/wiltondb/wiki/WiltonDB-Data-Transfer-GUI-tool#command-line-interface-to-data-transfer-tool).

There should be no changes at all to the GUI version, please let me know if you see discrepancies.

**Comment by psrinivasa2** [comment]
Thanks Alex, We will check it

**Comment by psrinivasa2** [comment]
HI Alex, 
Silent installation works fine, hope there should be generic option to saved the import and export entries into a log file. 
 
 
This can be closed

**Comment by staticlibs** [comment]
@psrinivasa2 

Thanks for confirming! 

Log files writing raises the questions about log append and log rotate. And I would like to not deal with these questions right now. And just writing a log file with something like:

```
wdb_transfer_cli.exe export ... --log-file log1.txt
```

is more or less the same as the shell output redirect:

```
wdb_transfer_cli.exe export ... > log1.txt 2>&1
```

and the latter is actually more flexible when calling from PowerShell scripts.
