### ISSUE TITLE
Install WiltonDB in Windows Container

### ISSUE THREAD

**Issue by shonarik** [wiltondb/wiltondb#5]
# Solution
The problem is that `msiexec.exe` does not accept relative paths when running as Administrator. In other words, where I previously wrote `".\wiltondb3.3_3.5.1.msi"` it must be `"C:\wiltondb3.3_3.5.1.msi"`. Also, remote connections are disabled by default which means that wdb cannot be accessed outside of the container. You must run `ALTER SYSTEM SET listen_addresses TO '*'` on the database and restart the service.

Here is the full script that worked:
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
Start-Process -filepath C:\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process
Remove-Item -Force vc_redist.x64.exe
Invoke-WebRequest "https://github.com/wiltondb/wiltondb/releases/download/3.3-3-5-1/wiltondb3.3_3.5.1.msi" -OutFile "wiltondb3.3_3.5.1.msi"
Start-Process -filepath "$Env:SystemRoot\system32\msiexec.exe" -ArgumentList "/package", "C:\wiltondb3.3_3.5.1.msi", "/quiet", "/passive", "/qn", "/L*V c:\wiltondb_install_log.txt" -Passthru | Wait-Process
Remove-Item -Force wiltondb3.3_3.5.1.msi
& powershell.exe -Command { $env:PGPASSWORD='wilton'; & "C:\Program Files\WiltonDB Software\wiltondb3.3\bin\psql.exe" -U wilton -c "ALTER SYSTEM SET listen_addresses TO '*'" }
Invoke-WebRequest "https://github.com/microsoft/go-sqlcmd/releases/download/v1.5.0/sqlcmd-x64_1.5.0-1.msi" -OutFile "sqlcmd-x64_1.5.0-1.msi"
Start-Process -filepath "$Env:SystemRoot\system32\msiexec.exe" -ArgumentList "/package", "C:\sqlcmd-x64_1.5.0-1.msi", "/quiet", "/passive", "/qn", "/norestart", "/L*V c:\sqlcmd-x64_1.5.0-1_install_log.txt" -Passthru | Wait-Process
Remove-Item -Force sqlcmd-x64_1.5.0-1.msi
& powershell.exe -Command { $env:SQLCMDPASSWORD='wilton'; & "C:\Program Files\SqlCmd\sqlcmd.exe" -S . -U wilton -Q "EXECUTE sp_babelfish_configure 'escape_hatch_rowversion', 'ignore', 'server'" }
& powershell.exe -Command { $env:SQLCMDPASSWORD='wilton'; & "C:\Program Files\SqlCmd\sqlcmd.exe" -S . -U wilton -Q "EXECUTE sp_babelfish_configure 'escape_hatch_nocheck_add_constraint', 'ignore', 'server'" }
Restart-Service wiltondb3.3
```

## Remarks
* the script above enables the following escape hatches:
  * `escape_hatch_rowversion`
  * `escape_hatch_nocheck_add_constraint`

# Description
Team, I'm trying to install WiltonDB in a Windows container for the purpose of providing a local test environment that must work alongside other Windows Containers. To keep things simple within both developer workstations and CI/CD runners, dependencies are built into containers which produces that same environment regardless of host.

I've used the following `docker` commands to get into a `powershell` environment where WiltonDB is to be installed:
* Full Windows Container: `docker run -it mcr.microsoft.com/windows:20H2-KB5016616-amd64 powershell`
* Server Core Container: `docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 powershell`

Neither base image seems to work with WiltonDB. Here are the commands that I've run within the container to install both the VC++ runtime and WiltonDB:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
Start-Process -filepath C:\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process
Remove-Item -Force vc_redist.x64.exe
Invoke-WebRequest "https://github.com/wiltondb/wiltondb/releases/download/3.3-3-5-1/wiltondb3.3_3.5.1.msi" -OutFile "wiltondb3.3_3.5.1.msi"
Start-Process -filepath "$Env:SystemRoot\system32\msiexec.exe" -ArgumentList "/i", ".\wiltondb3.3_3.5.1.msi", "/qn", "/L*V c:\wiltondb_install_log.txt" -Passthru | Wait-Process
Remove-Item -Force wiltondb3.3_3.5.1.msi
```

It appears that WiltonDB is not installed - here is the log output:

```
=== Verbose logging started: 1/5/2024  15:00:08  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (38:74) [15:00:08:079]: Resetting cached policy values
MSI (c) (38:74) [15:00:08:079]: Machine policy value 'Debug' is 0
MSI (c) (38:74) [15:00:08:079]: ******* RunEngine:
           ******* Product: .\wiltondb3.3_3.5.1.msi
           ******* Action:
           ******* CommandLine: **********
MSI (c) (38:74) [15:00:08:094]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (38:74) [15:00:08:094]: Grabbed execution mutex.
MSI (c) (38:74) [15:00:08:110]: Cloaking enabled.
MSI (c) (38:74) [15:00:08:110]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (38:74) [15:00:08:110]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (7C:90) [15:00:08:125]: Running installation inside multi-package transaction C:\.\wiltondb3.3_3.5.1.msi
MSI (s) (7C:90) [15:00:08:125]: Grabbed execution mutex.
MSI (s) (7C:A0) [15:00:08:141]: Resetting cached policy values
MSI (s) (7C:A0) [15:00:08:141]: Machine policy value 'Debug' is 0
MSI (s) (7C:A0) [15:00:08:141]: ******* RunEngine:
           ******* Product: C:\.\wiltondb3.3_3.5.1.msi
           ******* Action:
           ******* CommandLine: **********
MSI (s) (7C:A0) [15:00:08:141]: Machine policy value 'DisableUserInstalls' is 0
MSI (s) (7C:A0) [15:00:08:141]: Note: 1: 2203 2: C:\Windows\Installer\inprogressinstallinfo.ipi 3: -2147287038
MSI (s) (7C:A0) [15:00:08:157]: SRSetRestorePoint skipped for this transaction.
MSI (s) (7C:A0) [15:00:08:157]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2
MSI (s) (7C:A0) [15:00:08:157]: Note: 1: 1324 2: . 3: 1
MSI (s) (7C:A0) [15:00:08:157]: MainEngineThread is returning 2
MSI (s) (7C:90) [15:00:08:157]: No System Restore sequence number for this installation.
MSI (s) (7C:90) [15:00:08:157]: User policy value 'DisableRollback' is 0
MSI (s) (7C:90) [15:00:08:157]: Machine policy value 'DisableRollback' is 0
MSI (s) (7C:90) [15:00:08:157]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (7C:90) [15:00:08:172]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2
MSI (s) (7C:90) [15:00:08:172]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2
MSI (s) (7C:90) [15:00:08:172]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (38:74) [15:00:08:172]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (38:74) [15:00:08:172]: MainEngineThread is returning 2
=== Verbose logging stopped: 1/5/2024  15:00:08 ===
```

How can I help? I feel like this will further the adoption of Wilton for those looking to develop against Babelfish.

# Updates
* the same issue occurs when running outside of a container - it looks like the issue is running the MSI unattended

**Comment by shonarik** [comment]
WiltonDB appears to be listening on port 1433- verified with `netstat -nta` however it is not accessible from outside the container. According to this Wiki, I can use a GUI - `wdg_config.exe` to allow remote connections:
* https://github.com/wiltondb/wiltondb/wiki/Allowing-remote-connections

How can this be done programmatically?

**Comment by staticlibs** [comment]
Thanks a lot for all the details on solving these issues!

On running inside Windows containers, I've created a [new wiki page](https://github.com/wiltondb/wiltondb/wiki/Running-inside-Windows-containers) and copied your scripts there.

On remote access, as you've likely already figured out, `netstat` output should show `0.0.0.0:1433` and `0.0.0.0:5432` instead of default localhost-only `127.0.0.1:1433` and `127.0.0.1:5432`. I've added a [note to the wiki page](https://github.com/wiltondb/wiltondb/wiki/Allowing-remote-connections#allowing-remote-connections) about [other ways to set system parameters](https://www.postgresql.org/docs/15/config-setting.html).

**Comment by shonarik** [comment]
Thanks for updating the Wiki with this content - glad I could help. One minor change is recommended:

* In [Escape hatches and T-SQL scripts](https://github.com/wiltondb/wiltondb/wiki/Running-inside-Windows-containers#escape-hatches-and-t-sql-scripts), you don't need to restart the service since those changes take effect immediately.
* Restarting the service was only required to allow remote connections.

**Comment by staticlibs** [comment]
Good catch! I've removed the restart call from that section in wiki.

**Comment by staticlibs** [comment]
Closing this as "completed", please re-open if needed.
