### ISSUE TITLE
Issue in one of the machine for accessing babelfish via hostname or localhost, but works in 127.0.0.1

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#51]
Hi Alex,
In one of my colleague machine, We are facing below issue in accessing the babelfish, any idea why this would be?

![image](https://github.com/user-attachments/assets/19123c5a-ba39-46b9-8387-b27991f22a81)

![image](https://github.com/user-attachments/assets/b7c5a14a-2923-4bdf-85f9-3032ebc2ce06)

![image](https://github.com/user-attachments/assets/7edb7923-fa63-4ad0-903e-2094413127cb)

**Comment by staticlibs** [comment]
@psrinivasa2 

Please check the `listen_addresses` config parameter on that instance. By default WiltonDB server only listens for connections on `127.0.0.1`. And `localhost` name may or may not be resolved to `127.0.0.1`. See more details on [this wiki page](https://github.com/wiltondb/wiltondb/wiki/Allowing-remote-connections).
