### ISSUE TITLE
Windows Install WiltonDB with migration_mode single-db

### ISSUE THREAD

**Issue by chriscameron-vertexinc** [wiltondb/wiltondb#6]
Hello!

I want to use WiltonDB on Windows for the local development of an application that is already built to run against an Aurora instance of Babelfish for Postgres.

My application needs to run in single-db mode, but it looks like the WiltonDB MSI installer files are hardcoded to multi-db mode:
https://github.com/wiltondb/wdb_windows_msi/blob/master/resources/wiltondb-setup-02.sql#L5

Ideally I'd expect the migration_mode to either have the same default as Babelfish (single-db) or the MSI should present a selection.

Alternatively, how would I go about re-initializing the database as single-db after installation?

**Comment by staticlibs** [comment]
DB cluster init with `single-db` mode should be easier to do now with [3.3-4-6-1 update](https://github.com/wiltondb/wiltondb/releases/tag/3.3-4-6-1).

`-MigrationMode single-db` option can be used now with `wiltondb-setup.ps1`, all supported options are [documented here](https://github.com/wiltondb/wiltondb/wiki/Running-under-non%E2%80%90privileged-user#configuring-db-cluster-init-options).

And `icacls` call from previous comment is only necessary if custom DB cluster is going to be used with default Windows service.

I'll close this issue as "completed", please re-open if there are more questions on this.

PS: on default migration mode:

> have the same default as Babelfish (single-db)

It seems that this is no longer the case and the default Aurora Babelfish migration mode is [changed to multi-db in 4.0](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraBabelfish.Updates.html#AuroraBabelfish.Updates.40X).
