### ISSUE TITLE
The data base name selection list box does not display all the database names in the instance to select for the wilton db tools.

### ISSUE THREAD

**Issue by ManojKumar-emis** [wiltondb/wiltondb#73]
The data base name selection list box does not allow to select the required database name when there are many databases in the instance.
Assume there are many databases in the instance which is selected for data export/import using the Wilton db transfer tool (or any similar tools like backup-restore). E.g. 30+ databases. Because of the limitation of the maximum number of data base names which can be displayed within the list box for the selection of database names, facing the issue of selecting the required database from the instance which will not be displayed because there is no scroll bar to scroll down. If we try to use the navigation keys or trying to type the first letter to navigate to those database names starting with that letter, the tool is being closed.
If there is scroll bar also to select the required database `name` from the list of all database names in the instance, it would be helpful.
Work around for those who are facing the same issue : Rename the required database to show on top like with a prefix '1'. Then after finishing the work, rename back to the original.

**Comment by staticlibs** [comment]
Thanks for the report! Apparently keyboard navigation on the dropdown list works correctly in `wdb_backup`, but is broken in `wdb_transfer`.

**Comment by staticlibs** [comment]
Fixed this in [wdb_transfer-1.4.1](https://github.com/wiltondb/wdb_transfer/releases/tag/1.4.1).

Unfortunately the GUI library does not support the mouse wheel scroll in this list. Keyboard scroll should work fine. The tables list reload now happens when the dropdown is closed. It also happens when it is closed with the same value as before or closed on escape key - this can be improved in future.

**Comment by ManojKumar-emis** [comment]
Thank you. Hope the keyboard navigation issue will be resolved for wb_transfer also.

**Comment by staticlibs** [comment]
@ManojKumar-emis 

> Hope the keyboard navigation issue will be resolved for wb_transfer also.

The change in `1.4.1` was for `wdb_transfer`, for DB names drop down on Export tab. Other drop downs in `wdb_transfer` and `wdb_backup` worked correctly for me.

**Comment by ManojKumar-emis** [comment]
Thank you for the resolution provided for wdb_transfer.

**Comment by staticlibs** [comment]
Closing as completed.
