### ISSUE TITLE
UNION could not convert type "varchar" to tinyint

### ISSUE THREAD

**Issue by staticlibs** [wiltondb/wiltondb#78]
_Originally posted by @psrinivasa2 in https://github.com/wiltondb/wiltondb/issues/53#issuecomment-2434162313_

**Comment by staticlibs** [comment]
@psrinivasa2 

This should be [already fixed](https://github.com/wiltondb/babelfish_extensions/commit/fef0376fad54fa38e03912e015f7808863cca2a6) in the latest dev version,  please try running the following on Postgres connection to apply the fix to the `11.16.0.rc6` version:

```sql
CREATE OR REPLACE FUNCTION sys.varchar2tinyint(sys.VARCHAR)
RETURNS sys.TINYINT
AS 'babelfishpg_common', 'varchar2tinyint'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE CAST (sys.VARCHAR AS sys.TINYINT)
WITH FUNCTION sys.varchar2tinyint(sys.VARCHAR) AS IMPLICIT;

CREATE OR REPLACE FUNCTION sys.tinyint2varchar(sys.TINYINT)
RETURNS sys.VARCHAR
AS $$
  SELECT $1::SMALLINT;
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE CAST (sys.TINYINT AS sys.VARCHAR)
WITH FUNCTION sys.tinyint2varchar(sys.TINYINT) AS IMPLICIT;
```

**Comment by psrinivasa2** [comment]
For now I should manually add, In further release you will include this right?

**Comment by staticlibs** [comment]
@psrinivasa2 

Yes, it this is correct, this fix will be automatically included with newly created DB clusters, and on the existing cluster you will need to run the following after the MSI upgrade:

```sql
ALTER EXTENSION "babelfishpg_common" UPDATE TO '3.3.4'
```

**Comment by staticlibs** [comment]
@psrinivasa2 

> please try running the following on Postgres connection to apply the fix to the `11.16.0.rc6` version:

Sorry, this won't actually run directly in PgAdmin:

```
ERROR:  cast from type sys."varchar" to type sys.tinyint already exists 
```

This must go through the `ALTER EXTENSION` instead, I will prepare the update script and will post it here in a few minutes.

**Comment by staticlibs** [comment]
@psrinivasa2

Please save this attached file [babelfishpg_common--3.3.3--3.3.4.sql.txt](https://github.com/user-attachments/files/17503345/babelfishpg_common--3.3.3--3.3.4.sql.txt) on path: 

```
C:\Program Files\WiltonDB Software\wiltondb3.3\share\extension\babelfishpg_common--3.3.3--3.3.4.sql
``` 

(note, remove the `.txt` suffix) and then run the following in PgAdmin in `wilton` DB:

```sql
ALTER EXTENSION "babelfishpg_common" UPDATE TO '3.3.4'
```

You can check the resulting version with:

```sql
select * from pg_extension
```

**Comment by staticlibs** [comment]
The fix to this is included in [12.16.1 update](https://github.com/wiltondb/wiltondb/releases/tag/3-lts-12-16-1).

**Comment by psrinivasa2** [comment]
Thanks @staticlibs

**Comment by psrinivasa2** [comment]
This can be closed
