### ISSUE TITLE
To understand Extended property method names plan

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#82]
Hi @staticlibs ,
We would like to use below method names for implementation regarding table/column/constraint/index description. Before we use these function names, we wanted to understand any plan in future from babelfish/wiltonDB/postgreSQL side to use it, if so our implementation may get overridden. Do you have any idea?

sys.fn_listextendedproperty
 sys.sp_dropextendedproperty
sys.sp_addextendedproperty

**Comment by staticlibs** [comment]
@psrinivasa2 

These 3 functions are already used in Babelfish to handle extended properties. For user-defined functions I suggest to not place them into `sys` schema. And if it is necessary to place them there - then to add an app-specific prefix for them.

**Comment by psrinivasa2** [comment]
Okay @staticlibs
