### ISSUE TITLE
Primary key order is changed after updating table in Babelfish

### ISSUE THREAD

**Issue by Aravind2601** [wiltondb/wiltondb#92]
Hi @staticlibs,

we are facing one issue in babelfish like after updating the table the row order is changed. 
Before update:
![image](https://github.com/user-attachments/assets/2ae14f94-32fa-40ba-90ba-0c990ec30619)
After update:
![image](https://github.com/user-attachments/assets/88197fdb-49f1-4014-9147-c8b85b0a7472)
Could you please help us on this?

**Comment by staticlibs** [comment]
@Aravind2601 

Please share the SQL query you are using to get this result set.

**Comment by Aravind2601** [comment]
@staticlibs , please find the query .
select * from dbo.persons

**Comment by staticlibs** [comment]
@Aravind2601 

And why the results of this query are expected to be sorted in any particular way?

**Comment by Aravind2601** [comment]
By default, table order is maintained based on primary key . In SQL, its maintaining order but only here it is reordered after update

**Comment by staticlibs** [comment]
@Aravind2601 

One still needs to run an SQL query to see this data. If such query does not have `ORDER BY`, then the result set order is indeterminate in any RDBMS.

**Comment by psrinivasa2** [comment]
@Aravind2601  As discussed, even in SQL their is no guarantee for primary key order without ORDER BY. Our application should have considered ORDER BY in all our cases. Hence, we can ignore this issue.

@staticlibs You can close this.
